### ISSUE TITLE
Tweet new issues

### ISSUE THREAD

**Issue by rubenvanerk** [ash-jc-allen/find-a-pr#102]
To increase the reach of issues that need help, we could tweet them automatically.

**Comment by ash-jc-allen** [comment]
I think that'd actually be a really cool feature! Off the top of my head, I think we'll need to store some info about the issues so that we can track which ones have/haven't been tweeted.

I think if we approach this right, it could also open up the opportunity to post the issues on other sites too in the future (e.g. - LinkedIn, Telegram) 😄

**Comment by jaetoole** [comment]
@ash-jc-allen We could have this setup on a scheduled command (infrastructure dependent) that dispatched a job to crawl the repos. Then we dispatch a job which just calls a few actions (or we could use Laravel Notifications I guess) for dispatching the details (from the DTO) to each social channel. That way, we would only have to store a log either in the database or just to whichever logging solution you use of each issue number.

Just thinking of different ways to implement this whilst still keeping the codebase as light as possible.

**Comment by ash-jc-allen** [comment]
Yeah, I'm definitely on board with that approach. I've not spent any time looking into if there's a way to send tweets from Laravel notifications, but if possible, that'd be pretty cool to use.

I'm thinking that we'd maybe have a `social_posts` table in the DB (I'm definitely open to a better name though) with something fields like:

- `id`
- `issue_repo` - (e.g. - `ash-jc-allen/find-a-pr`)
- `issue_number`
- `twitter_url`
- `twitter_sent_at`
- `created_at`
- `updated_at`

I'm half tempted to add an `issues` table in the database, but I'm trying to use the GitHub API as the single source of truth to keep the maintenance as easy as possible. What's your opinion on adding an `issues` table?

Do you have any thoughts on any of this too @rubenvanerk?

**Comment by jaetoole** [comment]
The tweets is the easy bit. I'm opposed to storing a copy of every Github issue. Think of if the application gets large etc, we've either got to have webhooks to update issues (not sure if that's a thing on the GH API) or we have to scrape GH's API for it.

Your table structure is pretty much what I was thinking. `issue_repo` and `issue_number` is more 'humanly readable' than the unique `issue_id` in the GH API. I'm not opposed to storing that too though.

@rubenvanerk if you're taking this on, I'd be more than happy to help if you like?

**Comment by ash-jc-allen** [comment]
@rubenvanerk Ahh nice, I didn't actually know that there were unique identifiers across all of GitHub. In that case, I think it'd be worth storing the `issue_id` too just on the off-chance that we want it for any future features.

I'll get a "Find A PR" Twitter account set up at some point this week or next week so that it's prepped ready for us to use :)

**Comment by ash-jc-allen** [comment]
This has been deployed now, so I'll close this issue :)
